'use client'

import './globals.css'
import { Inter } from 'next/font/google'

import {SessionProvider} from "next-auth/react"
import Navbar from '@/components/Navbar'
import "../node_modules/react-quill/dist/quill.snow.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children,session }) {
  return (
    
    <html lang="en">
      <SessionProvider session={session}>
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
    </SessionProvider>
    </html>
  )
}
